name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          enablement: true
      
      - name: Create artifact directory
        run: |
          mkdir -p ./artifact
          cp index.html ./artifact/
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './artifact'  # 使用新创建的目录
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
